"""create instruments table

Revision ID: 2872cdb2b12a
Revises: bac433f58fd9
Create Date: 2026-07-26 23:05:53.821899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2872cdb2b12a'
down_revision: Union[str, Sequence[str], None] = 'bac433f58fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('base_asset', sa.String(length=30), nullable=True),
    sa.Column('quote_asset', sa.String(length=30), nullable=True),
    sa.Column('market_data_provider', sa.String(length=50), nullable=False),
    sa.Column('provider_symbol', sa.String(length=100), nullable=False),
    sa.Column('supports_latest', sa.Boolean(), nullable=False),
    sa.Column('supports_history', sa.Boolean(), nullable=False),
    sa.Column('supports_sentiment', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_asset_type'), 'instruments', ['asset_type'], unique=False)
    op.create_index(op.f('ix_instruments_code'), 'instruments', ['code'], unique=True)
    op.create_index(op.f('ix_instruments_is_active'), 'instruments', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_is_active'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_code'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_asset_type'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
