"""create market candles hypertable

Revision ID: 681a87a453cd
Revises: 72fa21184068
Create Date: 2026-07-28 12:51:19.934120

"""
from typing import Sequence, Union  # noqa: UP035

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '681a87a453cd'
down_revision: Union[str, Sequence[str], None] = '72fa21184068'  # noqa: UP007
branch_labels: Union[str, Sequence[str], None] = None  # noqa: UP007
depends_on: Union[str, Sequence[str], None] = None  # noqa: UP007


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_candles',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('instrument_id', 'interval', 'timestamp')
    )
    op.execute(
        "CREATE EXTENSION IF NOT EXISTS timescaledb"
    )
    op.execute(
        """
        SELECT create_hypertable(
            'market_candles',
            'timestamp',
            if_not_exists => TRUE
        );
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_candles')
    # ### end Alembic commands ###
